/*
 * lab_5_se.asm
 *
 *  Created: 21-05-2020 12:43:52
 *   Author: chaitanya
 */ 

 .INCLUDE "M32DEF.INC"
.EQU KEY_PIN=PINA
.EQU KEY_DDR=DDRA
.EQU KEY_PORT=PORTA
.EQU LCD_PRT = PORTC
.EQU LCD_DDR = DDRC
.EQU LCD_PIN = PINC
.EQU LCD_RS = 0
.EQU LCD_RW = 1
.EQU LCD_EN = 2


LDI R16,HIGH(RAMEND)
OUT SPH,R16
LDI R16,LOW(RAMEND)
OUT SPL,R16

LDI ZH,HIGH(MYDATA<<1)
LDI ZL,LOW(MYDATA<<1)

LDI R16,0
OUT KEY_DDR,R16
LDI R16,0xFF
OUT KEY_PORT,R16
OUT DDRB,R16
LDI R21,0XFF
OUT LCD_DDR,R21
OUT LCD_DDR,R21

LDI R16,0X33
CALL COMMAND_W
CALL DELAY_2ms

LDI R16,0X32
CALL COMMAND_W
CALL DELAY_2ms

LDI R16,0X28
CALL COMMAND_W
CALL DELAY_2ms

LDI R16,0X0E
CALL COMMAND_W

LDI R16,0X01
CALL COMMAND_W
CALL DELAY_2ms

LDI R16,0xC0
CALL COMMAND_W

LDI R16,0X06
CALL COMMAND_W

WAIT_FOR_RELEASE:
					NOP 
					IN R17,KEY_PIN
					CPI R17,0xFF
					BRNE WAIT_FOR_RELEASE
KEY_PRESS:		
					IN R17,KEY_PIN
					CPI R17,0xFF
					BREQ KEY_PRESS	
					LDI R19,0xFF
					IN R17,KEY_PIN
					MOV R18,R17
					SEC

L1:
					ROR R18
					INC R19
					BRCS L1
	   				OUT PORTB,R19	
					LDI ZL,LOW(MYDATA<<1)
					ADD ZL,R19
			 
					LPM R16,Z
					CALL DATA_W
					JMP WAIT_FOR_RELEASE
COMMAND_W:
					MOV R27,R16
					ANDI R27,0XF0
					IN R26,LCD_PIN
					ANDI R26,0X0F
					OR R26,R27
					OUT LCD_PRT,R26
					CBI LCD_PRT,LCD_RW
					CBI LCD_PRT,LCD_RS
					SBI LCD_PRT,LCD_EN
					NOP
					CBI LCD_PRT,LCD_EN
					CALL DELAY_100us
					MOV R27,R16
					SWAP R27
					ANDI R27,0XF0
					IN R26,LCD_PIN
					ANDI R26,0X0F
					OR R26,R27
					OUT LCD_PRT,R26
					SBI LCD_PRT,LCD_EN
					NOP
					CBI LCD_PRT,LCD_EN
					CALL DELAY_100us
					RET


DATA_W:
					MOV R27,R16
					ANDI R27,0XF0
					IN R26,LCD_PIN
					ANDI R26,0X0F
					OR R26,R27
					OUT LCD_PRT,R26
					CBI LCD_PRT,LCD_RW
					SBI LCD_PRT,LCD_RS
					SBI LCD_PRT,LCD_EN
					CALL SDELAY
					CBI LCD_PRT,LCD_EN
					MOV R27,R16
					SWAP R27
					ANDI R27,0XF0
					IN R26,LCD_PIN
					ANDI R26,0X0F
					OR R26,R27
					OUT LCD_PRT,R26
					SBI LCD_PRT,LCD_EN
					call SDELAY
					CBI LCD_PRT,LCD_EN
					CALL DELAY_100us
					RET

SDELAY:
					NOP
					NOP
					RET

					DELAY_100us:
					PUSH R17
					LDI R17,60
					DR0:
					CALL SDELAY
					DEC R17
					BRNE DR0
					POP R17
					RET

DELAY_2ms:
					PUSH R17
					LDI R17,20
			LDR0:	CALL DELAY_100us
					DEC R17
					BRNE LDR0
					POP R17
					RET	

DELAY_15ms:
					PUSH R17
					LDI R17,150
			LDR1:   CALL DELAY_100us
					DEC R17
					BRNE LDR1
					POP R17
					RET


.ORG 0x500
MYDATA:
			.DB '0','1','2','3','4','5','6','7'
